# Iman Noor
---
<h1 style="font-size:36px; font-family:Verdana, sans-serif; color:navy; text-align:center; font-weight:bold;">
    NLP PREPROCESSING
</h1>

Natural Language Processing (NLP) preprocessing is a crucial step in preparing textual data for analysis and model building. It involves a series of techniques to clean and transform raw text into a format that can be effectively processed by machine learning algorithms. The primary goal of NLP preprocessing is to reduce noise, standardize text, and extract meaningful features that can improve the performance of NLP models.

Key steps in NLP preprocessing include:

1. **Tokenization**: Splitting text into individual units, such as words or sentences, which serve as the building blocks for further analysis.

2. **Lowercasing**: Converting all text to lowercase to ensure uniformity and reduce the complexity of the vocabulary.

3. **Removing Punctuation**: Eliminating punctuation marks to focus on the words themselves and avoid unnecessary symbols in the analysis.

4. **Stopword Removal**: Removing common words (e.g., "and", "the", "is") that do not carry significant meaning and may clutter the data.

5. **Stemming and Lemmatization**: Reducing words to their base or root form. Stemming chops off prefixes and suffixes, while lemmatization considers the word's context and reduces it to its dictionary form.

6. **Removing Special Characters**: Eliminating non-alphanumeric characters, such as hashtags, mentions, or emojis, to clean the text further.

7. **Handling Numerical Data**: Converting or removing numbers in the text depending on their relevance to the task.

8. **Text Normalization**: Standardizing text by expanding contractions (e.g., "can't" to "cannot"), correcting misspellings, and normalizing word forms.

9. **Removing Rare Words or Characters**: Filtering out words or characters that appear infrequently, which may not contribute significantly to the analysis.

Some of the main key steps are as follows:

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center; font-weight:bold;">
    DATA PREPARATION
</h1>

In [1]:
import pandas as pd

In [2]:
formal_df = pd.read_csv('news_articles.csv')
print('Formal Dataset Preview:\n')
formal_df.head()

Formal Dataset Preview:

,Article_Id,Title,Author,Date,Content,URL
0,0,14 dead after bus falls into canal in Telangan...,Devyani Sultania,"August 22, 2016 12:34 IST",At least 14 people died and 17 others were inj...,http://www.ibtimes.co.in/14-dead-after-bus-fal...
1,1,Pratibha Tiwari molested on busy road Saath ...,Suparno Sarkar,"August 22, 2016 19:47 IST",TV actress Pratibha Tiwari who is best known ...,NaN
2,2,US South Korea begin joint military drill ami...,Namrata Tripathi,"August 22, 2016 18:10 IST",The United States and South Korea began a join...,http://www.ibtimes.co.in/us-south-korea-begin-...
3,3,Illegal construction in Bengaluru Will my hou...,S V Krishnamachari,"August 22, 2016 17:39 IST",The relentless drive by Bengaluru s Bangalore...,http://www.ibtimes.co.in/illegal-construction-...
4,4,Punjab Gau Rakshak Dal chief held for assaulti...,Pranshu Rathee,"August 22, 2016 17:34 IST",Punjab Gau Raksha Dal chief Satish Kumar and h...,http://www.ibtimes.co.in/punjab-gau-rakshak-da...

<h1 style="font-size:30px; font-family:Verdana, sans-serif; color:navy;">
    PREPROCESSING TECHNIQUES
</h1>

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    TOKENIZATION
</h1>


Tokenization is a fundamental step in the preprocessing of text data in Natural Language Processing (NLP). It involves breaking down a stream of text into smaller, manageable units called tokens. Tokens can be words, sentences, or even subwords, depending on the level of tokenization required for the task.

#### Types of Tokenization:

1. **Word Tokenization**: 
   - The text is split into individual words. This is the most common type of tokenization and is used in tasks where each word is treated as a separate unit.
   - Example: The sentence "Natural Language Processing is fascinating!" would be tokenized into ["Natural", "Language", "Processing", "is", "fascinating", "!"].

2. **Sentence Tokenization**:
   - The text is split into sentences. This type of tokenization is useful in tasks where sentence structure or the relationship between sentences is important.
   - Example: The paragraph "I love NLP. It's a very interesting field." would be tokenized into ["I love NLP.", "It's a very interesting field."].

3. **Subword Tokenization**:
   - The text is split into subword units, which can be useful for handling out-of-vocabulary words or languages with complex morphology.
   - Example: The word "unhappiness" might be tokenized into ["un", "happiness"].

In [3]:
# nltk.download('punkt')

In [4]:
import nltk
from nltk.tokenize import word_tokenize

In [5]:
formal_df['tokenized'] = formal_df['Content'].apply(word_tokenize)

In [6]:
print("Tokenized Formal Dataset:\n")
formal_df[['tokenized']].head()

Tokenized Formal Dataset:

                                           tokenized
0  [At, least, 14, people, died, and, 17, others,...
1  [TV, actress, Pratibha, Tiwari, who, is, best,...
2  [The, United, States, and, South, Korea, began...
3  [The, relentless, drive, by, Bengaluru, s, Ban...
4  [Punjab, Gau, Raksha, Dal, chief, Satish, Kuma...

#### Importance of Tokenization:

- **Facilitates Further Processing**: Tokenization provides a structured way to analyze text data, enabling further processing like part-of-speech tagging, parsing, and machine learning model input.
  
- **Handles Text Ambiguity**: By breaking down text into tokens, tokenization helps in managing ambiguity in language and allows more precise analysis.

- **Improves Model Efficiency**: Efficient tokenization can significantly impact the performance of NLP models by ensuring that text is parsed and represented in a way that aligns with the model's requirements.
---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    LOWERCASING
</h1>

Lowercasing is a simple yet essential preprocessing step in Natural Language Processing (NLP) that involves converting all the characters in a text to lowercase. This process helps standardize the text by reducing the variability caused by different cases (uppercase vs. lowercase) and ensures that words are treated uniformly, regardless of how they are capitalized in the original text.

#### Importance of Lowercasing:

1. **Uniformity in Text**:
   - Lowercasing helps create a consistent text format by ensuring that words like "Natural", "NATURAL", and "natural" are all treated as the same word. This uniformity is crucial for reducing the dimensionality of the text data.

2. **Improved Model Performance**:
   - By reducing the number of distinct words (i.e., different capitalizations of the same word), lowercasing can help improve the efficiency and performance of NLP models. It allows models to learn more effectively by focusing on the semantic meaning of words rather than their case variations.

3. **Simplicity in Matching**:
   - Lowercasing simplifies tasks like matching, searching, and comparing words. For example, in text search applications, converting all text to lowercase ensures that searches are case-insensitive, providing more accurate results.

4. **Handling Ambiguity**:
   - In some languages and contexts, the case of a word can change its meaning. However, in many NLP tasks, such as sentiment analysis or topic modeling, lowercasing is sufficient and can help avoid confusion caused by case variations.

#### When to Avoid Lowercasing:

- **Proper Nouns and Acronyms**: In tasks where proper nouns, acronyms, or case-sensitive information (e.g., "USA" vs. "usa") are important, lowercasing may not be appropriate, as it could lead to the loss of critical information.
- **Context-Sensitive Tasks**: For tasks that rely on case distinctions, such as Named Entity Recognition (NER) or certain forms of syntactic parsing, lowercasing might need to be applied selectively or not at all.

In [7]:
def lowercase_text(text):
    return text.lower()

In [8]:
formal_df['lowercased'] = formal_df['Content'].apply(lowercase_text)

In [9]:
print('Lowercased Formal Dataset:\n')
formal_df[['lowercased']].head()

Lowercased Formal Dataset:

                                          lowercased
0  at least 14 people died and 17 others were inj...
1  tv actress pratibha tiwari  who is best known ...
2  the united states and south korea began a join...
3  the relentless drive by bengaluru s  bangalore...
4  punjab gau raksha dal chief satish kumar and h...

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    REMOVING NON-WORD & NON-WHITESPACE CHARACTERS
</h1>

In [10]:
formal_df['non_whitespace'] = formal_df['Content'].replace(to_replace=r'[^\w\s]', value='', regex=True)

In [11]:
print('Formal Dataset after removing non-word and non-whitespace characters:\n')
formal_df[['non_whitespace']].head()

Formal Dataset after removing non-word and non-whitespace characters:

                                      non_whitespace
0  At least 14 people died and 17 others were inj...
1  TV actress Pratibha Tiwari  who is best known ...
2  The United States and South Korea began a join...
3  The relentless drive by Bengaluru s  Bangalore...
4  Punjab Gau Raksha Dal chief Satish Kumar and h...

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    REMOVING URLs
</h1>

In [12]:
formal_df = formal_df.dropna(subset=['URL'])

In [13]:
import re

# Define a regex pattern to match URLs
url_pattern = re.compile(r'https?://\S+')

# Define a function to remove URLs from text
def remove_urls(text):
    return url_pattern.sub('', text)

# Apply the function to the 'text' column and create a new column 'clean_text'
formal_df['non_url'] = formal_df['URL'].apply(remove_urls)

### As the entire content of the `URL` column consists only of the URL and when that URL is removed, nothing is left.

In [14]:
print('Formal Dataset after removing URL:\n')
formal_df[['URL', 'non_url']]

Formal Dataset after removing URL:

                                                    URL non_url
0     http://www.ibtimes.co.in/14-dead-after-bus-fal...
2     http://www.ibtimes.co.in/us-south-korea-begin-...
3     http://www.ibtimes.co.in/illegal-construction-...
4     http://www.ibtimes.co.in/punjab-gau-rakshak-da...
6     http://www.ibtimes.co.in/infosys-shares-likely...
...                                                 ...     ...
4825  http://www.ibtimes.co.in/iphone-6-vs-samsung-g...
4826  http://www.ibtimes.co.in/samsung-galaxy-s6-vs-...
4827  http://www.ibtimes.co.in/htc-latest-octa-core-...
4828  http://www.ibtimes.co.in/samsung-galaxy-s6-act...
4829  http://www.ibtimes.co.in/google-rolls-out-andr...

[3389 rows x 2 columns]

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    REMOVING DIGITS
</h1>

In [16]:
formal_df['without_digit'] = formal_df['Content'].replace(to_replace=r'\d', value='', regex=True)

In [17]:
print('Formal Dataset after removing digits:\n')
formal_df[['without_digit']].head()

Formal Dataset after removing digits:

                                       without_digit
0  At least  people died and  others were injured...
2  The United States and South Korea began a join...
3  The relentless drive by Bengaluru s  Bangalore...
4  Punjab Gau Raksha Dal chief Satish Kumar and h...
6  Infosys shares could fall sharply on Tuesday w...

### Just for better understanding we'll remove digits from 'Date'

In [18]:
formal_df['date_without_digit'] = formal_df['Date'].replace(to_replace=r'\d', value='', regex=True)

In [19]:
print('Formal Dataset after removing digits:\n')
formal_df[['date_without_digit']].head()

Formal Dataset after removing digits:

  date_without_digit
0    August ,  : IST
2    August ,  : IST
3    August ,  : IST
4    August ,  : IST
6    August ,  : IST

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    STOPWORD REMOVAL
</h1>

Stopword removal is a common preprocessing step in Natural Language Processing (NLP) that involves filtering out common words that appear frequently in text but carry little meaningful information. These words, known as stopwords, include articles, prepositions, conjunctions, and other commonly used words such as "the", "is", "in", "and", "but", and "or".

In [20]:
from nltk.corpus import stopwords

In [21]:
# nltk.download('stopwords')

In [22]:
stop_words = set(stopwords.words('english'))
formal_df['stopword'] = formal_df['Content'].apply(lambda x: [word for word in x if word not in stop_words])

In [23]:
print('After Stopword Removal:\n')
formal_df[['stopword']].head()

After Stopword Removal:

                                            stopword
0  [A,  , l, e,  , 1, 4,  , p, e, p, l, e,  , e, ...
2  [T, h, e,  , U, n, e,  , S, e,  , n,  , S, u, ...
3  [T, h, e,  , r, e, l, e, n, l, e,  , r, v, e, ...
4  [P, u, n, j, b,  , G, u,  , R, k, h,  , D, l, ...
6  [I, n, f,  , h, r, e,  , c, u, l,  , f, l, l, ...

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    STEMMING
</h1>

It involves reducing words to their root or base form by removing suffixes, prefixes, or other inflected forms. The primary goal of stemming is to treat words with the same root as equivalent, which helps in simplifying the text and reducing the dimensionality of the data.

#### How Stemming Works:

- Stemming algorithms, such as the **Porter Stemmer** or **Snowball Stemmer**, apply heuristic rules to strip suffixes and prefixes from words, often producing a root form that may not always be a valid word in the language.
- For example, the words "running", "runner", and "ran" might all be reduced to the stem "run". Similarly, "happiness" and "happy" might be reduced to "happi".

#### Considerations:

- **Crudeness of Stemming**:
   - Stemming is often considered a crude method because it relies on simple rules that can sometimes produce stems that are not actual words (e.g., "studies" might be stemmed to "studi"). This can lead to the loss of linguistic nuances.
  
- **Overstemming and Understemming**:
   - **Overstemming** occurs when a stemming algorithm reduces words to the same stem incorrectly (e.g., "universe" and "university" might be reduced to the same stem).
   - **Understemming** happens when words that should be reduced to the same stem are not (e.g., "connect" and "connected" might not be reduced to the same root).

- **When to Use Stemming**:
   - Stemming is most useful in scenarios where exact word forms are not critical, and the focus is on capturing the broader meaning of the text. It is commonly used in applications like search engines, text classification, and topic modeling.

In [24]:
from nltk.stem import PorterStemmer

In [25]:
# Initialize the Porter Stemmer
stemmer = PorterStemmer()

# Define a function to perform stemming on the 'text' column
def stem_words(words):
    return [stemmer.stem(word) for word in words]

# Define a function to perform stemming on the 'text' column
def stem_words(words):
    return [stemmer.stem(word) for word in words]

# Apply the function to the 'text' column and create a new column 'stemmed_text'
formal_df['stemmed_messages'] = formal_df['Content'].apply(stem_words)

In [26]:
print('Formal Dataset after Stemming:\n')
formal_df[['stemmed_messages']].head()

Formal Dataset after Stemming:

                                    stemmed_messages
0  [a, t,  , l, e, a, s, t,  , 1, 4,  , p, e, o, ...
2  [t, h, e,  , u, n, i, t, e, d,  , s, t, a, t, ...
3  [t, h, e,  , r, e, l, e, n, t, l, e, s, s,  , ...
4  [p, u, n, j, a, b,  , g, a, u,  , r, a, k, s, ...
6  [i, n, f, o, s, y, s,  , s, h, a, r, e, s,  , ...

---
<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    LEMMATIZATION
</h1>

Lemmatization is a text preprocessing technique in Natural Language Processing (NLP) that reduces words to their base or root form, known as the "lemma." Unlike stemming, which simply chops off prefixes or suffixes, lemmatization considers the context and morphological structure of the word, resulting in a valid word that belongs to the language.

#### How Lemmatization Works:

- Lemmatization uses linguistic knowledge, such as part-of-speech tags and the word's meaning, to determine the correct base form of a word. For example, the words "running", "ran", and "runs" are all reduced to the lemma "run".
- Lemmatization requires a detailed dictionary or a database that maps various word forms to their corresponding lemmas.

#### Examples:

- "Studies", "studying", and "studied" are all lemmatized to "study".
- "Children" is lemmatized to "child".
- "Was" and "were" are lemmatized to "be".

#### Considerations:

- **Complexity and Resource Intensity**:
   - Lemmatization is more computationally intensive than stemming because it requires a comprehensive understanding of the language's morphology and context. This complexity can lead to longer processing times, especially for large datasets.

- **Dependency on Accurate Part-of-Speech Tagging**:
   - Lemmatization often relies on accurate part-of-speech tagging to determine the correct lemma. For example, "running" could be a verb ("run") or a noun ("running"), and the correct lemma depends on its usage in the sentence.

- **Applications**:
   - Lemmatization is particularly useful in applications where the meaning and grammatical integrity of words are important, such as machine translation, information retrieval, and advanced text analytics.

In [27]:
# nltk.download('averaged_perceptron_tagger')
# nltk.download('wordnet')

In [28]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [29]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = word_tokenize(text)
    return [lemmatizer.lemmatize(word) for word in words]

formal_df['lemmatized'] = formal_df['Content'].apply(lambda x: ' '.join(lemmatize_text(x)))

In [30]:
print('Formal Dataset after Lemmatization:\n')
formal_df[['lemmatized']].head()

Formal Dataset after Lemmatization:

                                          lemmatized
0  At least 14 people died and 17 others were inj...
2  The United States and South Korea began a join...
3  The relentless drive by Bengaluru s Bangalore ...
4  Punjab Gau Raksha Dal chief Satish Kumar and h...
6  Infosys share could fall sharply on Tuesday wh...

In [31]:
formal_df.head()

,Article_Id,Title,Author,Date,Content,URL,tokenized,lowercased,non_whitespace,non_url,without_digit,date_without_digit,stopword,stemmed_messages,lemmatized
0,0,14 dead after bus falls into canal in Telangan...,Devyani Sultania,"August 22, 2016 12:34 IST",At least 14 people died and 17 others were inj...,http://www.ibtimes.co.in/14-dead-after-bus-fal...,"[At, least, 14, people, died, and, 17, others,...",at least 14 people died and 17 others were inj...,At least 14 people died and 17 others were inj...,,At least people died and others were injured...,"August , : IST","[A, , l, e, , 1, 4, , p, e, p, l, e, , e, ...","[a, t, , l, e, a, s, t, , 1, 4, , p, e, o, ...",At least 14 people died and 17 others were inj...
2,2,US South Korea begin joint military drill ami...,Namrata Tripathi,"August 22, 2016 18:10 IST",The United States and South Korea began a join...,http://www.ibtimes.co.in/us-south-korea-begin-...,"[The, United, States, and, South, Korea, began...",the united states and south korea began a join...,The United States and South Korea began a join...,,The United States and South Korea began a join...,"August , : IST","[T, h, e, , U, n, e, , S, e, , n, , S, u, ...","[t, h, e, , u, n, i, t, e, d, , s, t, a, t, ...",The United States and South Korea began a join...
3,3,Illegal construction in Bengaluru Will my hou...,S V Krishnamachari,"August 22, 2016 17:39 IST",The relentless drive by Bengaluru s Bangalore...,http://www.ibtimes.co.in/illegal-construction-...,"[The, relentless, drive, by, Bengaluru, s, Ban...",the relentless drive by bengaluru s bangalore...,The relentless drive by Bengaluru s Bangalore...,,The relentless drive by Bengaluru s Bangalore...,"August , : IST","[T, h, e, , r, e, l, e, n, l, e, , r, v, e, ...","[t, h, e, , r, e, l, e, n, t, l, e, s, s, , ...",The relentless drive by Bengaluru s Bangalore ...
4,4,Punjab Gau Rakshak Dal chief held for assaulti...,Pranshu Rathee,"August 22, 2016 17:34 IST",Punjab Gau Raksha Dal chief Satish Kumar and h...,http://www.ibtimes.co.in/punjab-gau-rakshak-da...,"[Punjab, Gau, Raksha, Dal, chief, Satish, Kuma...",punjab gau raksha dal chief satish kumar and h...,Punjab Gau Raksha Dal chief Satish Kumar and h...,,Punjab Gau Raksha Dal chief Satish Kumar and h...,"August , : IST","[P, u, n, j, b, , G, u, , R, k, h, , D, l, ...","[p, u, n, j, a, b, , g, a, u, , r, a, k, s, ...",Punjab Gau Raksha Dal chief Satish Kumar and h...
6,6,Infosys shares likely to fall on Tuesday after...,S V Krishnamachari,"August 15, 2016 16:03 IST",Infosys shares could fall sharply on Tuesday w...,http://www.ibtimes.co.in/infosys-shares-likely...,"[Infosys, shares, could, fall, sharply, on, Tu...",infosys shares could fall sharply on tuesday w...,Infosys shares could fall sharply on Tuesday w...,,Infosys shares could fall sharply on Tuesday w...,"August , : IST","[I, n, f, , h, r, e, , c, u, l, , f, l, l, ...","[i, n, f, o, s, y, s, , s, h, a, r, e, s, , ...",Infosys share could fall sharply on Tuesday wh...

<h1 style="font-size:25px; font-family:Verdana, sans-serif; color:navy; text-align:center;">
    THE END :)
</h1>